export const supaUrl = 'https://vtbzarnrukqecuphffem.supabase.co'

export const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Ynphcm5ydWtxZWN1cGhmZmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzI0OTEsImV4cCI6MjA1NDk0ODQ5MX0.FMruIMwUBZ4WgSj_EGlbtCaruZ1cZf7LkcF3jnYSgWw'