export const supaUrl = 'https://zpdeyzivzlsyvlnrqdcz.supabase.co'

export const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZGV5eml2emxzeXZsbnJxZGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTAyNzAsImV4cCI6MjA1NjI2NjI3MH0.ZXMr1XhwlPI0u1f5jR_r2y1jxrb3jXXCalvwuYGyaiU'